name: my_first_project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  mysql1: ^0.19.1
  crypto: ^3.0.0  # For password hashing


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
